# traefik.yaml
api:
  dashboard: false
  insecure: false
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8899"

log:
  level: DEBUG
  format: json

accessLog:
  filePath: "/dev/stdout"
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        Host: keep
        X-Forwarded-For: keep
        X-Forwarded-Proto: keep
        X-Real-IP: keep
    names:
      StartUTC: keep
      StartLocal: keep
      Duration: keep
      RetryAttempts: keep
      RouterName: keep

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addrouterslabels: false
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf.d
    watch: true

# Global HTTP config
http:
  middlewares:
    redirector-auth:
      forwardAuth:
        address: "http://redirector-dev:3000"
        trustForwardHeader: true
        authResponseHeaders:
          - "ServiceAddr"
          - "ServiceUrl"
          - "X-Forwarded-*"