services:
  redirector-dev:
    build:
      context: ..
      target: development
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app:cached
      - ./ext/zshrc:/home/developer/.zshrc
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      - rust-tools:/usr/local/cargo/bin
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - CARGO_HOME=/usr/local/cargo
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:3000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    init: true
    user: developer

    networks:
      - traefik

  traefik-frontend:
    image: traefik:v2.10
    container_name: traefik-frontend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard port
      - "8899:8899"  # Metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ext/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./ext/traefik-conf/:/etc/traefik/conf.d/:ro

    networks:
      - traefik

  # Example backend service that returns redirects
  redirect-backend:
    image: nginx:alpine
    container_name: redirect-backend
    volumes:
      - ./ext/nginx-redirect.conf:/etc/nginx/conf.d/backend.conf:ro
    networks:
      - traefik

networks:
  traefik:
    name: traefik

volumes:
  cargo-cache:
    name: redirector-cargo-cache
  target-cache:
    name: redirector-target-cache
  rust-tools:
    name: redirector-rust-tools
  etcd_data:
    name: redirector-etcd-data
